name: Automatic Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Create Python virtual environment
        run: python -m venv backend/venv
      - run: npm ci
        working-directory: frontend
      - run: make clean
      - run: make all
      - uses: actions/upload-artifact@v4
        with:
          name: electron-builds
          path: frontend/out/make/**
          if-no-files-found: ignore
