name: Electron CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm ci
        working-directory: frontend
      - run: npm run make
        working-directory: frontend
      - uses: actions/upload-artifact@v4
        with:
          name: electron-builds
          path: frontend/out/make/**
